name: Continuous CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest


    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

      # Install newman globally
      - name: Install newman
        run: |
         npm install -g newman
         npm install -g newman-reporter-slackreporter
         npm install -g newman-reporter-htmlextra

        # npm install 


      # Make directory to upload test results 
      - name: Make Directory for Results
        run: mkdir -p testResults

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # Run postman collection
      - name: Run Postman Collection
        run: |
          newman run ${{secrets.COLLECTION_URL}} --suppress-exit-code -r slackreporter --reporter-slackreporter-webhookurl ${{secrets.WEBHOOK_URL}} --reporter-slackreporter-token ${{secrets.OAUTH_TOKEN}} --reporter-slackreporter-chanel 'delphi-corinth-test'

       #  newman run https://api.getpostman.com/collections/10326541-047433a4-2e51-414c-bf43-9d9c87affa49?apikey=PMAK-6156cf4f2a449400290f4546-36e4c16a723c843b9e7d3fa795cc7a5731 -e https://api.getpostman.com/environments/10326541-c8efda3a-6719-4504-b7e9-59886123b2e7?apikey=PMAK-6156cf4f2a449400290f4546-36e4c16a723c843b9e7d3fa795cc7a5731 --suppress-exit-code -r slackreporter --reporter-slackreporter-webhookurl https://hooks.slack.com/services/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
       #  newman run https://api.getpostman.com/collections/10326541-047433a4-2e51-414c-bf43-9d9c87affa49?apikey=PMAK-6156cf4f2a449400290f4546-36e4c16a723c843b9e7d3fa795cc7a5731 -e https://api.getpostman.com/environments/10326541-c8efda3a-6719-4504-b7e9-59886123b2e7?apikey=PMAK-6156cf4f2a449400290f4546-36e4c16a723c843b9e7d3fa795cc7a5731
       #  newman run ${{secrets.COLLECTION_URL}} -e ${{secrets.ENVIRONMENT_URL}} -r htmlextra --reporter-htmlextra-hideRequestBody "Login" --reporter-htmlextra-export testResults/htmlreport.>


      # Upload the contents of Test Results directory to workspace
      - name: Output the run results
        uses: actions/upload-artifact@v2
        with:
         name: Corinth ${{steps.date.outputs.date}}
         path: testResults
